using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ClubBrugge.Erp.Application.Migrations
{
    public partial class MatchPlayerStats : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "MatchPlayerStats",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    MatchId = table.Column<int>(type: "int", nullable: false),
                    TeamId = table.Column<int>(type: "int", nullable: false),
                    TeamName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PlayerId = table.Column<int>(type: "int", nullable: false),
                    PlayerName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    PlayerMatchMinutes = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchNpXgPerShot = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchNpXg = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchNpShots = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchGoals = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchNpGoals = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchXa = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchKeyPasses = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchOpKeyPasses = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchAssists = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchThroughBalls = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchPassesIntoBox = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchOpPassesIntoBox = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchTouchesInsideBox = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchTackles = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchInterceptions = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchPossession = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchDribbledPast = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchDribblesFaced = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchDribbles = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchChallengeRatio = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchFouls = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchDispossessions = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchLongBalls = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchSuccessfulLongBalls = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchLongBallRatio = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchShotsBlocked = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchClearances = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchAerials = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchSuccessfulAerials = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchAerialRatio = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchPasses = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchSuccessfulPasses = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchPassingRatio = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchOpPasses = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchForwardPasses = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchBackwardPasses = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchSidewaysPasses = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchOpF3Passes = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchOpF3ForwardPasses = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchOpF3BackwardPasses = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchOpF3SidewaysPasses = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchNpShotsOnTarget = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchCrosses = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchSuccessfulCrosses = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchCrossingRatio = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchPenaltiesWon = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchPassesInsideBox = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchOpXa = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchOpAssists = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchPressuredLongBalls = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchUnpressuredLongBalls = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchAggressiveActions = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchTurnovers = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchCrossesIntoBox = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchSpXa = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchOpShots = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchTouches = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchPressureRegains = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchBoxCrossRatio = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchDeepProgressions = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchShotTouchRatio = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchFoulsWon = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchXgchain = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchOpXgchain = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchXgbuildup = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchOpXgbuildup = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchXgchainPerPossession = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchOpXgchainPerPossession = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchXgbuildupPerPossession = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchOpXgbuildupPerPossession = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchPressures = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchPressureDurationTotal = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchPressureDurationAvg = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchPressuredActionFails = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchCounterpressures = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchCounterpressureDurationTotal = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchCounterpressureDurationAvg = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchCounterpressuredActionFails = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchObv = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchObvPass = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchObvShot = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchObvDefensiveAction = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchObvDribbleCarry = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchObvGk = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchDeepCompletions = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchBallRecoveries = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchNpPsxg = table.Column<double>(type: "float", nullable: false),
                    PlayerMatchPenaltiesFaced = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchPenaltiesConceded = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchFhalfBallRecoveries = table.Column<int>(type: "int", nullable: false),
                    PlayerMatchAverageSpaceReceivedIn = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchAverageFhalfSpaceReceivedIn = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchAverageF3SpaceReceivedIn = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchBallReceiptsInSpace10 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchBallReceiptsInSpace2 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchBallReceiptsInSpace5 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchFhalfBallReceiptsInSpace10 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchFhalfBallReceiptsInSpace2 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchFhalfBallReceiptsInSpace5 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchF3BallReceiptsInSpace10 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchF3BallReceiptsInSpace2 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchF3BallReceiptsInSpace5 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchLbp = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchLbpCompleted = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchFhalfLbpCompleted = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchF3LbpCompleted = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchFhalfLbp = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchF3Lbp = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchObvLbp = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchFhalfObvLbp = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchF3ObvLbp = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchLbpReceived = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchFhalfLbpReceived = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchF3LbpReceived = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchAverageLbpToSpaceDistance = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchFhalfAverageLbpToSpaceDistance = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchF3AverageLbpToSpaceDistance = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchLbpToSpace10Received = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchFhalfLbpToSpace10Received = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchF3LbpToSpace10Received = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchLbpToSpace2Received = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchFhalfLbpToSpace2Received = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchF3LbpToSpace2Received = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchLbpToSpace5Received = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchFhalfLbpToSpace5Received = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchF3LbpToSpace5Received = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchAverageLbpToSpaceReceivedDistance = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchFhalfAverageLbpToSpaceReceivedDistance = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchF3AverageLbpToSpaceReceivedDistance = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchLbpToSpace10 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchFhalfLbpToSpace10 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchF3LbpToSpace10 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchLbpToSpace2 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchFhalfLbpToSpace2 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchF3LbpToSpace2 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchLbpToSpace5 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchFhalfLbpToSpace5 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchF3LbpToSpace5 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchPasses360 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchObvPasses360 = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchFhalfPasses360 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchFhalfObvPasses360 = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchF3Passes360 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchF3ObvPasses360 = table.Column<double>(type: "float", nullable: true),
                    PlayerMatchBallReceipts360 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchFhalfBallReceipts360 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatchF3BallReceipts360 = table.Column<int>(type: "int", nullable: true),
                    PlayerMatch360Minutes = table.Column<double>(type: "float", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MatchPlayerStats", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "MatchPlayerStats");
        }
    }
}
